ALTER TABLE Date
	ADD CONTRAINT CHK_DAY
		CHECK(day BETWEEN 1 AND 31) ENABLE;

ALTER TABLE Date
	ADD CONTRAINT CHK_MONTH
		CHECK(month BETWEEN 1 AND 12) ENABLE;

ALTER TABLE Date
	ADD CONTRAINT CHK_QUARTER
		CHECK(quarter BETWEEN 1 AND 4) ENABLE;

ALTER TABLE Date
	ADD CONTRAINT CHK_YEAR
		CHECK(year > 1900) ENABLE;

ALTER TABLE Customer
	ADD CONTRAINT CHK_CUSTTYPE
		CHECK(custType IN ('C', 'P') ENABLE;