ALTER TABLE DateTable
	ADD CONSTRAINT CHK_DAY
		CHECK(nDay BETWEEN 1 AND 31) ENABLE;

ALTER TABLE DateTable
	ADD CONSTRAINT CHK_MONTH
		CHECK(nMonth BETWEEN 1 AND 12) ENABLE;

ALTER TABLE DateTable
	ADD CONSTRAINT CHK_QUARTER
		CHECK(nQuarter BETWEEN 1 AND 4) ENABLE;

ALTER TABLE DateTable
	ADD CONSTRAINT CHK_YEAR
		CHECK(nYear > 1900) ENABLE;

ALTER TABLE Customer
	ADD CONTRAINT CHK_CUSTTYPE
		CHECK(custType IN ('C', 'P')) ENABLE;